apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: dbaas-manual
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: lab-only-not-a-real-secret
  POSTGRES_DB: appdb
