apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-creds
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.dbPassword }}
  POSTGRES_DB: {{ .Values.dbName }}
